[package]
name = "genesis"
version = "0.1.0"
authors = ["Brian Collins <bricollins@gmail.com>"]

[dependencies]
piston = "0.18.0"
piston2d-graphics = "0.15.0"
piston2d-opengl_graphics = "0.23.0"
pistoncore-glutin_window = "0.21.0"
